global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"
 
 
scrape_configs:
  - job_name: "tf-serving"
    scrape_interval: 5s 
    metrics_path: /monitoring/prometheus/metrics 
    scheme: https
    static_configs:
      - targets: ['ml-ops-telco-production.up.railway.app']